apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - gke-acurast-prod-highcpu-pool-1-cc9066a5-oef3
      containers:
        - name: postgres
          image: postgres:16-alpine
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "__POSTGRES_ADMIN_USER__"
            - name: POSTGRES_DB
              value: "acurast-canary"
            - name: POSTGRES_PASSWORD
              value: "__POSTGRES_ADMIN_PASSWORD__"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-pv
              subPath: "pg_data"
          resources:
            requests:
              cpu: "0.5"
              memory: 400M
            limits:
              cpu: "1"
              memory: 1500M

      volumes:
        - name: postgres-pv
          persistentVolumeClaim:
            claimName: postgres-pv-claim
