kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: faster
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-backup-pvc
  labels:
    app: postgres
spec:
  storageClassName: faster
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi