include:
  - project: "papers/papers-internal/internal"
    file: "/.base-gitlab-ci.yml"
  - component: gitlab.papers.tech/papers/papers-internal/ci-cd-components/publish-local-registry@v0.0.44
    inputs:
      existing-tag: $GOOGLE_TAG-development
      tag-to-publish: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  - component: gitlab.papers.tech/papers/papers-internal/ci-cd-components/deploy-self-hosted-dev@v0.0.44
    inputs:
      extends_script: .deploy-script-dev
      environment: development
      url: bitcoin-regtest.dev.cluster.papers.tech

variables:
  TEST_TAG: $CI_PROJECT_NAME:test_$CI_COMMIT_SHA
  NAMESPACE: acurast-indexer

stages:
  - build
  - publish
  - deploy
  - provision
  - drop

.base_build:
  stage: build
  script:
    - docker build --build-arg RUN_ENV=$CI_ENVIRONMENT_NAME -t $GOOGLE_TAG-$CI_ENVIRONMENT_NAME .

build-dev:
  stage: build
  script:
    - !reference [.base_build, script]
  environment:
    name: development
    action: prepare

.base-deploy-script:
  script:
    - find k8s -type f -name \*.yaml -exec sed -i "s|__NAMESPACE_NAME__|"$NAMESPACE"|g" {} +
    - find k8s -type f -name \*.yaml -exec sed -i "s|__PROJECT_NAME__|"$CI_PROJECT_NAME"|g" {} +
    - find k8s -type f -name \*.yaml -exec sed -i "s|__TO_BE_REPLACED_BY_IMAGE_TAG__|"$IMAGE_TAG"|g" {} +

    - find k8s -type f -name \*.yaml -exec sed -i "s|__ENDPOINT__|"$ENDPOINT"|g" {} +
    - find k8s -type f -name \*.yaml -exec sed -i "s|__CHAIN_ID__|"$CHAIN_ID"|g" {} +
    - find k8s -type f -name \*.yaml -exec sed -i "s|__POSTGRES_ADMIN_USER__|"$POSTGRES_ADMIN_USER"|g" {} +
    - find k8s -type f -name \*.yaml -exec sed -i "s|__POSTGRES_ADMIN_PASSWORD__|"$POSTGRES_ADMIN_PASSWORD"|g" {} +

    - find k8s -type f -name \*.yaml -exec sed -i "s|__GRAFANA_ADMIN_USER__|"$POSTGRES_ADMIN_USER"|g" {} +
    - find k8s -type f -name \*.yaml -exec sed -i "s|__GRAFANA_ADMIN_PASSWORD__|"$POSTGRES_ADMIN_PASSWORD"|g" {} +
    - find k8s -type f -name \*.yaml -exec sed -i "s|__GRAFANA_SERVER_ROOT_URL__|"$GRAFANA_SERVER_ROOT_URL"|g" {} +
    - find k8s -type f -name \*.yaml -exec sed -i "s|__POSTGRES_HOST__|"$POSTGRES_HOST"|g" {} +
    - find k8s -type f -name \*.yaml -exec sed -i "s|__GRAFANA_DB_USER__|"$GRAFANA_DB_USER"|g" {} +
    - find k8s -type f -name \*.yaml -exec sed -i "s|__GRAFANA_DB_PASSWORD__|"$GRAFANA_DB_PASSWORD"|g" {} +

    - kubectl apply -k k8s/$CI_ENVIRONMENT_NAME/

.deploy-script-dev:
  extends: .base-deploy-script
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    ENDPOINT: wss://canarynet-ws-1.acurast-h-server-2.papers.tech
    CHAIN_ID: 0xce7681fb12aa8f7265d229a9074be0ea1d5e99b53eedcec2deade43857901808
    POSTGRES_HOST: postgres.$NAMESPACE:5432
    GRAFANA_SERVER_ROOT_URL: https://acurast-grafana.dev.cluster.papers.tech
