apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  labels:
    app: processor
spec:
  selector:
    matchLabels:
      app: processor
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: processor
    spec:
      # affinity:
      #   nodeAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #       - weight: 1
      #         preference:
      #           matchExpressions:
      #             - key: kubernetes.io/hostname
      #               operator: In
      #               values:
      #                 - gke-acurast-prod-highcpu-pool-1-cc9066a5-oef3
      containers:
        - name: processor
          image: __TO_BE_REPLACED_BY_IMAGE_TAG__
          command: ["yarn", "start-raw-processor"]
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: processor-config-map
            - secretRef:
                name: processor-secret
          env:
            - name: RAW_DATA_ENABLED
            - value: true
          readinessProbe:
            httpGet:
              path: /metrics
              port: 3000
            initialDelaySeconds: 60
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /metrics
              port: 3000
            initialDelaySeconds: 60
            timeoutSeconds: 5
          resources:
            requests:
              cpu: "0.2"
              memory: 600M
            limits:
              cpu: "1"
              memory: 1000M
      restartPolicy: Always
status: {}
