apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: __PROJECT_NAME__
  namespace: __NAMESPACE_NAME__
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - __PROJECT_NAME__.dev.cluster.papers.tech
        - acurast-grafana.dev.cluster.papers.tech
      secretName: __PROJECT_NAME__-prod-tls
  rules:
    - host: __PROJECT_NAME__.dev.cluster.papers.tech
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: explorer
                port:
                  number: 80
    - host: acurast-grafana.dev.cluster.papers.tech
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: grafana
                port:
                  number: 3000
