# # config file version
apiVersion: 1

# # list of datasources that should be deleted from the database
#deleteDatasources:
#   - name: Graphite
#     orgId: 1

# list of datasources to insert/update depending
# on what's available in the database
datasources:
- name: Acurast Custom Index
  # <string, required> datasource type. Required
  type: postgres
  # <string, required> access mode. direct or proxy. Required
  access: direct
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: __POSTGRES_HOST__
  # <string> database password, if used
  password: __GRAFANA_DB_PASSWORD__
  # <string> database user, if used
  user: __GRAFANA_DB_USER__
  # <string> database name, if used
  database: acurast-canary
  # <bool> mark as default datasource. Max one per org
  isDefault: true
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: true
  jsonData:
    sslmode: "disable"
