kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
secretGenerator:
  - name: grafana-files
    files:
      - datasource.yaml
resources:
  - pvc.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
